services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
         DEV: "true"
    container_name: code_grunt_app
    image: code_grunt:latest
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/code_grunt_db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["python", "main.py"]
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: postgres:16.5-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: code_grunt_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
