services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
         DEV: "true"
    container_name: code_grunt_app
    image: code_grunt:latest
    # env_file: 
    #   - .env
    # environment:
    #   OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["python", "main.py"]
    # depends_on:
    #   - db (if you have an external service like a separate database)
    # networks:
    #   - codegrunt_net

# If you ever use another service, such as an external database (Postgres, Redis, etc.),
# db:
#   image: postgres:16
#   environment:
#     POSTGRES_USER: user
#     POSTGRES_PASSWORD: pass
#     POSTGRES_DB: codegruntdb
#   volumes:
#     - db_data:/var/lib/postgresql/data
#   networks:
#     - codegrunt_net
# networks:
#   codegrunt_net:
